Actevia_Project/urls.py
from django.contrib import admin
from django.urls import path
from Firstapp import views
from Firstapp.views import searchEmployeeInfo
from Firstapp.views import show
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.urls import path, include
from Actevia_Project.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path("admin/", admin.site.urls),
    path("signup", views.SignupPage,name='signup'),
    path("",views.LoginPage,name='login'),
    path("emp" , views.emp),
    path("logout",views.LogoutPage,name='logout'),
    path("edit/<int:id>" , views.edit),
    path("update/<int:id>" , views.update),
    path("delete/<int:id>" , views.delete),
    path("edit1/<int:id>" , views.edit1),
    path("update1/<int:id>" , views.update1),
    path("edit2/<int:id>" , views.edit2),
    path("update2/<int:id>" , views.update2),
    path("delete1/<int:id>" , views.delete1),
    path("delete2/<int:id>" , views.delete2),
    path("Search",views.searchEmployeeInfo, name="search"),
    path("recruiter",views.recruiter),
    path("hr",views.hr),
    path("show",views.show),
    path("show1",views.show1),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

Firstapp/models.py
from django.db import models
from django.contrib.admin.widgets import AdminSplitDateTime

status = (
    ("Available","Available"),
    ("Engaged","Engaged"),
)

r_status = (
    ("Open", "Open"),
    ("Open", "Closed"),
)

onboarding_status = (
    ("YES", "YES"),
    ("NO", "NO"),
)

class Employee(models.Model):
    name = models.CharField(max_length= 100)
    yearofexp = models.FloatField()
    education = models.CharField(max_length = 300)
    keyskills = models.CharField(max_length= 500)
    detailedskills = models.TextField()
    interviewscore = models.CharField(max_length=4)
    prefferedworklocation = models.CharField(max_length=500)
    currentsalary = models.FloatField()
    expectedsalary = models.FloatField()
    doj = models.CharField(max_length= 300)
    status = models.CharField(max_length=20 , choices=status , default="Available")
    class Meta:
        db_table = "employee"


class Recruiter(models.Model):
    rid = models.CharField(max_length=5)
    companyname = models.CharField(max_length=30)
    jobarea = models.CharField(max_length=30)
    resourcerequired = models.FloatField()
    jd = models.TextField()
    resourceremaining = models.FloatField()
    r_status = models.CharField(max_length=20 , choices=r_status , default="open")
    class Meta:
        db_table = "resources"

    def __str__(self):
        return self.rid

class HR(models.Model):
    hrid = models.ForeignKey(Recruiter,blank=True, null=True,on_delete=models.CASCADE)
    file = models.FileField()
    L1interviewername = models.CharField(max_length=100)
    L1interviewdatetime  = models.DateTimeField(null=True)
    L2interviewername = models.CharField(max_length=100)
    L2interviewdatetime  = models.DateTimeField(null=True)
    status = models.CharField(max_length=20 , choices=r_status , default="open")
    onboarding = models.CharField(max_length=20 , choices=onboarding_status , default="YES")
    class Meta:
        db_table = "hr"

    def __str__(self):
        return f"{self.createdAt.strftime('%d-%m-%Y')}"

Firstapp/forms.py
from django import forms
from Firstapp.models import Employee
from Firstapp.models import Recruiter
from Firstapp.models import HR
from django.contrib.admin.widgets import AdminSplitDateTime


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        '''fields = ("slno","name","yearofexp","education","keyskills","detailedskills","interviewscore","prefferedworklocation",
        "currentsalary","expectedsalary","doj")'''
        fields = "__all__"
        
class ResourceForm(forms.ModelForm):
    class Meta:
        model = Recruiter
        fields = "__all__"

class HRForm(forms.ModelForm):
   # L1interviewdatetime = forms.SplitDateTimeField(widget=AdminSplitDateTime())
    #L2interviewdatetime = forms.SplitDateTimeField(widget=AdminSplitDateTime())
    class Meta:
        model = HR
        fields = "__all__"
    
    '''def __init__(self, *args, **kwargs):
        super(HRForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'''

class HRForm1(forms.Form):
    data_time_input = forms.DateField(widget=AdminSplitDateTime())

Firstapp/views.py
from django.shortcuts import render, redirect,HttpResponse
from Firstapp.forms import EmployeeForm
from Firstapp.forms import ResourceForm
from Firstapp.forms import HRForm
from Firstapp.models import Employee
from Firstapp.models import Recruiter
from Firstapp.models import HR
from Firstapp.templates.functions import handle_upload_file
from .filters import FilterEmployeeInfo
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/Search")
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, "index.html", {'form':form})


def show(request):
    employees = Recruiter.objects.all()
    return render(request, "show.html", {'employees': employees})

def show1(request):
    employees = HR.objects.all()
    return render(request, "show1.html", {'employees': employees})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, "edit.html", {'employee': employee})

def edit1(request, id):
    employee = Recruiter.objects.get(id=id)
    return render(request, "edit1.html", {'employee': employee})

def edit2(request, id):
    employee = HR.objects.get(id=id)
    return render(request, "edit2.html", {'employee': employee})

def update(request, id):
    employee = Employee.objects.get(id = id)
    form = EmployeeForm(request.POST, instance= employee)
    if form.is_valid():
        form.save()
        return redirect('/Search')
    return render(request, "edit.html", {'employee':employee})

def update1(request, id):
    employee = Recruiter.objects.get(id = id)
    form = ResourceForm(request.POST, instance= employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, "edit1.html", {'employee':employee})

def update2(request, id):
    employee = HR.objects.get(id = id)
    form = HRForm(request.POST, instance= employee)
    if form.is_valid():
        form.save()
        return redirect('/show1')
    return render(request, "edit2.html", {'employee':employee})

def delete(request, id):
    employee = Employee.objects.get(id = id)
    employee.delete()
    return redirect("/Search")

def delete1(request, id):
    employees = Recruiter.objects.get(id = id)
    employees.delete()
    return redirect("/show")

def delete2(request, id):
    employees = HR.objects.get(id = id)
    employees.delete()
    return redirect("/show1")

def searchEmployeeInfo(request):
    employee = Employee.objects.all()
    filters = FilterEmployeeInfo(request.GET, queryset=employee)  
    context = {'filters': filters}
    return render(request,"search.html" , context)

'''def search1EmployeeInfo(request):
    employee = Recruiter.objects.all()
    filters = FilterEmployeeInfo(request.GET, queryset=employee)  
    context = {'filters': filters}
    return render(request,"search1.html" , context)'''

def SignupPage(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        
        if pass1!=pass2:
            return HttpResponse("Your password and confrom password are not Same!!")
        else:
            my_user=User.objects.create_user(uname,email,pass1)
            my_user.save()
            return redirect('login')
    
    return render (request,'signup.html')
    

def LoginPage(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('pass')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request,user)
            return redirect('/Search')
        else:
            return HttpResponse ("Username or Password is incorrect!!!")

    return render (request,'login.html')

def LogoutPage(request):
    logout(request)
    return redirect('login')

def recruiter(request):
    if request.method == "POST":
        form1 = ResourceForm(request.POST)
        if form1.is_valid():
            try:
                form1.save()
                return redirect("/show")
            except:
                pass
    else:
        form1 = ResourceForm()
    return render(request, "index1.html", {'form1':form1})

def hr(request):
    if request.method == "POST":
        form1 = HRForm(request.POST, request.FILES)
        if form1.is_valid():
            try:
                handle_upload_file(request.FILES['file'])
                model_instance = form1.save(commit=False)
                model_instance.save()
                form1.save()
                return redirect("/show1")
            except:
                pass
    else:
        form1 = HRForm()
    return render(request, "index2.html", {'form1':form1})

    
            

Firstapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}" >
        {% csrf_token %}
    <div class="container">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name :</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Year of Exp :</label>
    <div class="col-sm-4">
        <input type="text" name="yearofexp" id="id_yearofexp" required maxlength="100" value="{{ employee.yearofexp }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Education :</label>
    <div class="col-sm-4">
        <input type="text" name="education" id="id_education" required maxlength="300" value="{{ employee.education }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Key Skills :</label>
    <div class="col-sm-4">
        <input type="text" name="keyskills" id="id_keyskills" required maxlength="500" value="{{ employee.keyskills }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Detailed Skills :</label>
    <div class="col-sm-4">
        <input type="text" name="detailedskills" id="id_detailedskills" required maxlength="100" value="{{ employee.detailedskills }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Interview Score :</label>
    <div class="col-sm-4">
        <input type="text" name="interviewscore" id="id_interviewscore" required maxlength="4" value="{{ employee.interviewscore }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Preffered Work Location :</label>
    <div class="col-sm-4">
        <input type="text" name="prefferedworklocation" id="id_prefferedworklocation" required maxlength="500" value="{{ employee.prefferedworklocation }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Expected Salary :</label>
    <div class="col-sm-4">
        <input type="text" name="currentsalary" id="id_currentsalary" required maxlength="10" value="{{ employee.currentsalary }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Rate Card :</label>
    <div class="col-sm-4">
        <input type="text" name="expectedsalary" id="id_expectedsalary" required maxlength="10" value="{{ employee.expectedsalary }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date of Join :</label>
    <div class="col-sm-4">
        <input type="text" name="doj" id="id_doj" required maxlength="10" value="{{ employee.doj }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Status :</label>
    <div class="col-sm-4">
        <input type="text" name="status" id="id_status" required maxlength="10"  value="{{ employee.status }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-sucess">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Firstapp/templates/edit1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index1</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
    <form method="POST" class="post-form" action="/update1/{{employee.id}}" >
        {% csrf_token %}
    <div class="container">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">SL ID :</label>
    <div class="col-sm-4">
        <input type="text" name="rid" id="id_rid" required maxlength="5" value="{{ employee.rid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Company Name :</label>
    <div class="col-sm-4">
        <input type="text" name="companyname" id="id_companyname" required maxlength="30" value="{{ employee.companyname }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Job Area :</label>
    <div class="col-sm-4">
        <input type="text" name="jobarea" id="id_jobarea" required maxlength="30" value="{{ employee.jobarea }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Resources Required :</label>
    <div class="col-sm-4">
        <input type="text" name="resourcerequired" id="id_resourcerequired" required maxlength="10" value="{{ employee.resourcerequired }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Job Description :</label>
    <div class="col-sm-4">
        <input type="text" name="jd" id="id_jd" required maxlength="1000" value="{{ employee.jd }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Resource Remaining :</label>
    <div class="col-sm-4">
        <input type="text" name="resourceremaining" id="id_resourceremaining" required maxlength="10" value="{{ employee.resourceremaining }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Status :</label>
    <div class="col-sm-4">
        <input type="text" name="r_status" id="id_r_status" required maxlength="10" value="{{ employee.r_status }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-sucess">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Firstapp/templates/edit2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index1</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
    <form method="POST" class="post-form" action="/update2/{{employee.id}}" >
        {% csrf_token %}
    <div class="container">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ID :</label>
    <div class="col-sm-4">
        <input type="text" name="hrid" id="id_hrid" required maxlength="5" value="{{ employee.hrid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Upload File :</label>
    <div class="col-sm-4">
        <input type="file" name="file" id="id_file"  value="{{ employee.file }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L1 Interviewer Name :</label>
    <div class="col-sm-4">
        <input type="text" name="L1interviewername" id="id_L1interviewername" required maxlength="30" value="{{ employee.L1interviewername }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L1 Interview Date_Time:</label>
    <div class="col-sm-4">
        <input type="DATETIME" name="L1interviewdatetime" id="id_L1interviewdatetime" required maxlength="30" value="{{ employee.L1interviewdatetime }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L2 Interviewer Name :</label>
    <div class="col-sm-4">
        <input type="text" name="L2interviewername" id="id_L2interviewername" required maxlength="30" value="{{ employee.L2interviewername }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L2 Interview Date_Time :</label>
    <div class="col-sm-4">
        <input type="DATETIME" name="L2interviewdatetime" id="id_L2interviewdatetime" required maxlength="30" value="{{ employee.L2interviewdatetime }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Status :</label>
    <div class="col-sm-4">
        <input type="text" name="status" id="id_status" required maxlength="30" value="{{ employee.status }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Onboarding Status :</label>
    <div class="col-sm-4">
        <input type="text" name="onboarding" id="id_onboarding" required maxlength="10" value="{{ employee.onboarding }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-sucess">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Firstapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">  
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/emp" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="container-fluid">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name :</label>
    <div class="col-sm-4">
        {{ form.name }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Year of Exp :</label>
    <div class="col-sm-4">
        {{ form.yearofexp }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Education :</label>
    <div class="col-sm-4">
        {{ form.education }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Key Skills :</label>
    <div class="col-sm-4">
        {{ form.keyskills }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Detailed Skills :</label>
    <div class="col-sm-4">
        {{ form.detailedskills }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Interview Score :</label>
    <div class="col-sm-4">
        {{ form.interviewscore }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Preffered Work Location :</label>
    <div class="col-sm-4">
        {{ form.prefferedworklocation }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Expected Salary :</label>
    <div class="col-sm-4">
        {{ form.currentsalary }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Rate Card :</label>
    <div class="col-sm-4">
        {{ form.expectedsalary }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date of Join :</label>
    <div class="col-sm-4">
        {{ form.doj }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Status :</label>
    <div class="col-sm-4">
        {{ form.status }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-danger">Submit</button>
    </div>
  </div>
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

Firstapp/templates/index1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">  
<head>
    <meta charset="UTF-8">
    <title>Index1</title>
    
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/recruiter" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="container-fluid">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">SL ID :</label>
    <div class="col-sm-4">
        {{ form1.rid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Company Name :</label>
    <div class="col-sm-4">
        {{ form1.companyname }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Job Area :</label>
    <div class="col-sm-4">
        {{ form1.jobarea }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Resource Required :</label>
    <div class="col-sm-4">
        {{ form1.resourcerequired }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">JD :</label>
    <div class="col-sm-4">
        {{ form1.jd }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Remaining_resources :</label>
    <div class="col-sm-4">
        {{ form1.resourceremaining }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Resources Status :</label>
    <div class="col-sm-4">
        {{ form1.r_status }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-danger">Submit</button>
    </div>
  </div>
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

Firstapp/templates/index2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">  
<head>
    <meta charset="UTF-8">
    <title>Index2</title>
    
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/hr" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
    <div class="container-fluid">
<br>
<img src="{% static 'img/logo.png' %}" alt="My image">
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>    
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">HR ID :</label>
    <div class="col-sm-4">
        {{ form1.hrid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">File :</label>
    <div class="col-sm-4">
        {{ form1.file }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L1 Interviwer Name :</label>
    <div class="col-sm-4">
        {{ form1.L1interviewername }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L1 Interview Date and Time :</label>
    <div class="col-sm-4">
        {{ form1.L1interviewdatetime }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L2 Interviwer Name :</label>
    <div class="col-sm-4">
        {{ form1.L2interviewername }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">L2 Interview Date and Time :</label>
    <div class="col-sm-4">
        {{ form1.L2interviewdatetime }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"> Status :</label>
    <div class="col-sm-4">
        {{ form1.status }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Onboarding Status :</label>
    <div class="col-sm-4">
        {{ form1.onboarding }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-danger">Submit</button>
    </div>
  </div>
    </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>